# Generated by Django 3.0.6 on 2020-05-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('correo_usuario', models.CharField(max_length=80, unique=True)),
                ('nombre_usuario', models.CharField(max_length=40, unique=True)),
                ('contraseña', models.CharField(max_length=60)),
                ('foto_usuario', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
