# Generated by Django 3.0.6 on 2020-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('correo_usuario', models.EmailField(default='', max_length=254, unique=True)),
                ('nombre_usuario', models.CharField(default='', max_length=40, unique=True)),
                ('contraseña', models.CharField(default='', max_length=60)),
                ('foto_usuario', models.ImageField(default='', upload_to='media')),
            ],
        ),
    ]
