# Generated by Django 3.0.6 on 2020-05-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(upload_to='mediaS'),
        ),
    ]
