# Generated by Django 3.0.6 on 2020-05-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200521_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_usuario',
        ),
    ]
