# Generated by Django 3.0.6 on 2020-05-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
