# Generated by Django 3.0.6 on 2020-05-24 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foro', models.CharField(default='Foro', max_length=50, unique=True)),
                ('descripcion_foro', models.CharField(default='Un foro de foroverflow', max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_foro', models.ImageField(default='', upload_to='forum_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('id_foro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foro.Foro')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_comentario', models.TextField(default='')),
                ('votos_comentario', models.IntegerField(default=0)),
                ('id_post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foro.Post')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
