# Generated by Django 3.0.6 on 2020-05-21 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id_foro', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nombre_foro', models.CharField(default='Foro', max_length=50, unique=True)),
                ('descripcion_foro', models.CharField(default='Un foro de foroverflow', max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_foro', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('titulo_post', models.CharField(default='', max_length=200)),
                ('contenido_post', models.TextField(default='')),
                ('votos_post', models.IntegerField(default=0)),
                ('id_foro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foro.Foro')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('contenido_comentario', models.TextField(default='')),
                ('votos_comentario', models.IntegerField(default=0)),
                ('id_post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foro.Post')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
