# Generated by Django 3.0.6 on 2020-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20200523_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='foto_foro',
            field=models.ImageField(default='', upload_to='forum_pics'),
        ),
    ]
