# Generated by Django 3.0.6 on 2020-05-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20200523_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votos_post',
        ),
    ]
